
# Script to manually edit the instance parameters (eg comments, names, etc.)

new_line = "COMMENT: Generated by Finucane, Fulcher, O'Sullivan, and Seth (2021)"


ns = ["20", "50", "100", "200", "500", "1000"]
depots = ["centre", "corner"]
traffics = ["weekday_offpeak", "weekday_peak", "weekend_peak"]
rains = ["heavy", "mild", "low"]


for domain in ["dublin_centre", "m50", "dublin_south"]:
    for n in ns:
        for depot in depots:
            for traffic in traffics:
                for rain in rains:


                    if domain == "dublin_south" and n == "1000":
                        print("Ignore this combo")

                    else:

                        path = "instances/{}/{}_rainfall/{}/{}_n{}.gvrp".format(domain, rain, traffic, depot, n)
                        f = open(path)
                        data = f.readlines()
                        data[1] = new_line

                        with open(path, 'w') as file:
                            file.writelines( data )
